apiVersion: v1
kind: Service
metadata:
  name: <svc-name>
  namespace: <svc-ns
spec:
  type: ClusterIP
  selector:
    app: <app-label>
  ports:
    - protocol: TCP
      port: <svc-port>
      targetPort: <container-port>