apiVersion: v1
kind: Service
metadata:
  name: <svc-name>
  namespace: <svc-ns>
spec:
  type: NodePort
  selector:
    vmtype: linux
# The port you select must be available on all the nodes and in the range 30000 to 32767.
# If you do not provide the nodePort parameter, then Kubernetes selects an available port.
  ports:
    - protocol: TCP
      port: 22  2
      targetPort: 22
      nodePort: 30022 