apiVersion: v1
kind: Service
metadata:
  name: <svc-name>
  namespace: <svc-ns
spec:
  type: ClusterIP
  selector:
    app: <app-label>
  ports:
    - protocol: TCP
      port: <svc-port>
      targetPort: <container-port>

# The DNS Operator creates a record for service name

# The namespace that hosts the VM

# The selector that matches the label you define in the vm resource

# The service listens on port and forwards the requests to the targetPort inside the container

